"""Godot 4.x file templates.

Everything here emits **Godot 4** text resources (CLAUDE.md §6). Never 3.x:
``config_version=5``, ``CharacterBody2D``, ``move_and_slide()`` with no args, etc.
"""

from __future__ import annotations

# Name of the autoload-free harness scene/script the adapter injects for screenshots.
SCREENSHOT_SCENE = "_playsmith_screenshot.tscn"
SCREENSHOT_SCRIPT = "_playsmith_screenshot.gd"

# The verify harness — runs headless, evaluates gameplay assertions, prints PLAYSMITH_ASSERT.
VERIFY_SCENE = "_playsmith_verify.tscn"
VERIFY_SCRIPT = "_playsmith_verify.gd"


def project_godot(name: str, main_scene: str | None = None) -> str:
    """A minimal, valid Godot 4 ``project.godot``.

    Uses the GL Compatibility renderer — the right default for 2D and the one that
    exports cleanly to HTML5 and runs on low-end hardware.
    """
    lines = [
        "; Engine configuration file.",
        "; Generated by Playsmith. Safe to edit in the Godot 4 editor.",
        "",
        "config_version=5",
        "",
        "[application]",
        "",
        f'config/name="{name}"',
    ]
    if main_scene:
        lines.append(f'run/main_scene="{main_scene}"')
    lines += [
        'config/features=PackedStringArray("4.3", "GL Compatibility")',
        "",
        "[rendering]",
        "",
        'renderer/rendering_method="gl_compatibility"',
        'renderer/rendering_method.mobile="gl_compatibility"',
        "",
    ]
    return "\n".join(lines)


def trivial_main_scene() -> str:
    """A do-nothing Node2D scene — enough to prove the engine runs (engine-check)."""
    return '[gd_scene format=3 uid="uid://playsmith_trivial"]\n\n[node name="Main" type="Node2D"]\n'


def node2d_scene_with_script(root_name: str, script_res: str) -> str:
    """A Node2D scene whose root has a script attached."""
    return (
        "[gd_scene load_steps=2 format=3]\n\n"
        f'[ext_resource type="Script" path="{script_res}" id="1"]\n\n'
        f'[node name="{root_name}" type="Node2D"]\n'
        'script = ExtResource("1")\n'
    )


def screenshot_harness_script() -> str:
    """A GDScript harness that instances a target scene, renders a few frames, saves a PNG.

    Output path and target scene come from environment variables so we don't have to
    rewrite the script per call. Note: a real display (or xvfb on Linux) is required —
    ``--headless`` uses a dummy renderer that produces a blank image.
    """
    return (
        "extends Node\n"
        "\n"
        "var _frames := 0\n"
        "\n"
        "func _ready() -> void:\n"
        '\tvar target := OS.get_environment("PLAYSMITH_TARGET_SCENE")\n'
        '\tif target != "":\n'
        "\t\tvar packed = load(target)\n"
        "\t\tif packed:\n"
        "\t\t\tadd_child(packed.instantiate())\n"
        "\n"
        "func _process(_delta: float) -> void:\n"
        "\t_frames += 1\n"
        "\tif _frames == 15:\n"
        '\t\tvar out := OS.get_environment("PLAYSMITH_SCREENSHOT")\n'
        '\t\tif out != "":\n'
        "\t\t\tvar img := get_viewport().get_texture().get_image()\n"
        "\t\t\timg.save_png(out)\n"
        "\t\tget_tree().quit()\n"
    )


def screenshot_harness_scene() -> str:
    """The scene that runs the screenshot harness script."""
    return (
        "[gd_scene load_steps=2 format=3]\n\n"
        f'[ext_resource type="Script" path="res://{SCREENSHOT_SCRIPT}" id="1"]\n\n'
        '[node name="PlaysmithScreenshot" type="Node"]\n'
        'script = ExtResource("1")\n'
    )


def verify_harness_script() -> str:
    """A GDScript probe that runs the game headless and prints PLAYSMITH_ASSERT lines.

    It instances the target scene, lets physics settle for ~90 frames, then evaluates a
    fixed vocabulary of gameplay checks (player_exists / player_on_floor / player_not_falling)
    against the first CharacterBody2D it finds. ``is_on_floor()`` is valid headless because
    physics runs without a display — that's the whole point of the assertion loop.
    """
    return (
        "extends Node\n"
        "\n"
        "var _frames := 0\n"
        "var _player: Node = null\n"
        "var _start_y := 0.0\n"
        "var _max_y := -1.0e20\n"
        "\n"
        "func _ready() -> void:\n"
        '\tvar target := OS.get_environment("PLAYSMITH_TARGET_SCENE")\n'
        '\tif target != "":\n'
        "\t\tvar packed = load(target)\n"
        "\t\tif packed:\n"
        "\t\t\tadd_child(packed.instantiate())\n"
        "\t_player = _find_body(self)\n"
        "\n"
        "func _find_body(node: Node) -> Node:\n"
        "\tif node is CharacterBody2D:\n"
        "\t\treturn node\n"
        "\tfor child in node.get_children():\n"
        "\t\tvar found = _find_body(child)\n"
        "\t\tif found != null:\n"
        "\t\t\treturn found\n"
        "\treturn null\n"
        "\n"
        "func _physics_process(_delta: float) -> void:\n"
        "\t_frames += 1\n"
        "\tif _player != null and _player is Node2D:\n"
        "\t\tvar y: float = _player.global_position.y\n"
        "\t\tif _frames == 1:\n"
        "\t\t\t_start_y = y\n"
        "\t\t_max_y = max(_max_y, y)\n"
        "\tif _frames >= 90:\n"
        "\t\t_emit()\n"
        "\n"
        "func _has_ui(node: Node) -> bool:\n"
        "\tif node is Label or node is RichTextLabel or node is Button:\n"
        "\t\treturn true\n"
        "\tfor child in node.get_children():\n"
        "\t\tif _has_ui(child):\n"
        "\t\t\treturn true\n"
        "\treturn false\n"
        "\n"
        "func _emit() -> void:\n"
        '\tvar wanted := OS.get_environment("PLAYSMITH_CHECKS").split(",", false)\n'
        "\tvar on_floor := false\n"
        '\tif _player != null and _player.has_method("is_on_floor"):\n'
        "\t\ton_floor = _player.is_on_floor()\n"
        "\tvar fell := (_max_y - _start_y) > 2000.0\n"
        "\tvar results := {\n"
        '\t\t"player_exists": _player != null,\n'
        '\t\t"player_on_floor": on_floor,\n'
        '\t\t"player_not_falling": not fell,\n'
        '\t\t"scene_loads": get_child_count() > 0,\n'
        '\t\t"has_dialogue_ui": _has_ui(self),\n'
        "\t}\n"
        "\tfor key in results.keys():\n"
        "\t\tif wanted.is_empty() or wanted.has(key):\n"
        '\t\t\tprint("PLAYSMITH_ASSERT ", key, "=", "true" if results[key] else "false")\n'
        "\tget_tree().quit()\n"
    )


def verify_harness_scene() -> str:
    """The scene that runs the verify harness script."""
    return (
        "[gd_scene load_steps=2 format=3]\n\n"
        f'[ext_resource type="Script" path="res://{VERIFY_SCRIPT}" id="1"]\n\n'
        '[node name="PlaysmithVerify" type="Node"]\n'
        'script = ExtResource("1")\n'
    )


def web_export_preset() -> str:
    """A minimal ``export_presets.cfg`` defining a single HTML5 "Web" preset."""
    return (
        "[preset.0]\n"
        '\nname="Web"\n'
        'platform="Web"\n'
        "runnable=true\n"
        "advanced_options=false\n"
        "dedicated_server=false\n"
        'custom_features=""\n'
        'export_filter="all_resources"\n'
        'include_filter=""\n'
        'exclude_filter=""\n'
        'export_path=""\n'
        "\n[preset.0.options]\n"
        "\nvariant/extensions_support=false\n"
        "vram_texture_compression/for_desktop=true\n"
        "vram_texture_compression/for_mobile=false\n"
        "html/export_icon=true\n"
        'html/custom_html_shell=""\n'
        'html/head_include=""\n'
        "html/canvas_resize_policy=2\n"
        "html/focus_canvas_on_start=true\n"
        "html/experimental_virtual_keyboard=false\n"
        "progressive_web_app/enabled=false\n"
    )
